### ISSUE TITLE
Tracking issue for `prost-gen`

### ISSUE THREAD

**Issue by kkocdko** [kkocdko/ksite#2]
* [x] Supports `package` which only contains `message`.
* [x] Supports `oneof` and `enum`.
* [x] Nested `message` and `enum`.
* [x] Name context and module path.
* [x] Identifier case converter with the same behaviour of `heck`.
* [ ] Refactor for more idiomatic compilation process.
* [ ] Fully `import` supports (workaround avaliable now).
* [ ] Supports `service`.
* [ ] Retains comments.

**Comment by kkocdko** [comment]
Crate path: [./src/crates/prost-gen](https://github.com/kkocdko/ksite/tree/main/src/crates/prost-gen)
